Feature: Primary user should be able to create a new case

  Scenario: CO should be able to create a new classes

#    Given navigate to "https://cmpdev2.dol.gov/suite/"
#    Then user is on "Login Page"
#    When user clicks on "I AGREE"
#    And user fills the text input fields as below:
#      | Username | newyorkco@dol.gov |
#      | Password | DOLDev#1          |
#    And user clicks on "SIGN IN"

  Given Login as "DORO"

